<div class="container">
    <div class="row">
        <div class="index-logo">
            <div class="logo"></div>
        </div>
        <div class="index-dog">
            <div class="dog"></div>
        </div>
    </div>
    <div class="index-body-content row">
        <div class="form-container col-md-12">
            <div class="index-signin-form col-md-5">
                <div class="well">
                    <h3>RETAIL MEMBERS</h3>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            Sign in
                        </div>
                    </div>
                    <form>
                        <div class="input-group input-group-lg">
                            <input type="email" class="form-control" placeholder="Email" aria-describedby="sizing-addon1">
                        </div>

                        <div class="input-group input-group-lg">
                            <input type="password" class="form-control" placeholder="Password" aria-describedby="sizing-addon1">
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="input-group input-group-sm">
                                    <a href="javascript:void(0)">Forgotten your password?</a>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="col-sm-offset-2">
                                        <div class="checkbox">
                                            <label>
                                                Remember me
                                                <input type="checkbox">
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <button type="button" class="btn btn-danger">Go Fetch.. Woof<img src="<?php echo $this->getSkinUrl('images/wave.png') ?>" width="20" alt="" /></button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="index-legal-verifier col-md-6">
                <div class="well">
                    <div class="row">
                        <h2>WELCOME TO PHOENIX BEERS</h2>
                        <h4>Are you of legal drinking age in your country?</h4>
                    </div>
                    <div class="row">
                        <div class="btnSection">
                            <button type="button" class="btn btn-danger">Yes</button>
                            <button type="button" class="btn btn-danger">No</button>
                        </div>
                    </div>
                    <div class="msgSection">
                        <div class="row">
                            <div class="liceneseDetails">
                                <h6>Licence Details</h6>
                                <p>No. 616 010 3052
                                    <br> Wholesaler’s Licence
                                    <br> Phoenix Beers Pty Ltd
                                    <br> A: Unit 8, 10 Dewar Street,
                                    <br> Morley WA 6062
                                    <br> P: 08 9275 0955</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="warningMsg">
                                <h6>Warning</h6>
                                <p>Under the Liquor Control Act 1988, it is an offence:
                                    <ul>
                                        <li>To sell or supply liquor to a person under the age of 18 years on licensed or regulated premises; or </li>
                                        <li>For a person under the age of 18 years to purchase, or attempt to purchase, liquor on licensed or regulated premises.</li>
                                    </ul>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>